BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Blobs" (
	"BlobID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"FK_FilePathID"	INTEGER NOT NULL,
	"BlobData"	BLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS "Settings" (
	"SettingID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"SettingKey"	TEXT NOT NULL UNIQUE,
	"SettingValue"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "FilePaths" (
	"FilePathID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"FilePath"	TEXT NOT NULL UNIQUE,
	"LastWriteTimeUtc"	INTEGER NOT NULL,
	"HashAlgorithm"	TEXT NOT NULL,
	"FileHash"	TEXT NOT NULL
);
INSERT INTO "Settings" ("SettingID","SettingKey","SettingValue") VALUES (1,'DatabaseVersion','4'),
 (2,'DatabaseRevision','0');
CREATE UNIQUE INDEX IF NOT EXISTS "Index_FilePath" ON "FilePaths" (
	"FilePath"	ASC
);
COMMIT;
